# Account Microservice

server:
  port: 8072

spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  application:
    name: "account-microservice"
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: "org.hibernate.dialect.H2Dialect"
  datasource:
    username: "sa"
    password: ""
    url: "jdbc:h2:mem:alinedb;MODE=MYSQL"
    driver-class-name: org.h2.Driver

app:
  security:
    secret-key: "ThisIsAGreatSecretKey!!!"
    jwt:
      secret-key: "ThisIsAJWTAuthenticationSecretKey"
